@isTest
public class ConstantTest {
    
    @isTest
    static void getValues(){
        System.assert(!String.isEmpty(Constant.OPPORTUNITY_INVESTMENT_IN_FINLEAP_RECORDTYPE_ID));
        System.assert(!String.isEmpty(Constant.OPPORTUNITY_ECOSYSTEM_RECORDTYPE_ID));
        System.assert(!String.isEmpty(Constant.OPPORTUNITY_GLOBAL_RELATED_FIELDSET));
        System.assert(!String.isEmpty(Constant.CONTACT_STANDARD_RECORDTYPE_ID));
        System.assert(!String.isEmpty(Constant.ACCOUNT_STANDARD_RECORDTYPE_ID));
        System.assert(!String.isEmpty(Constant.COMMUNICATION_PROFILE_ID));
        System.assert(!String.isEmpty(Constant.FINLEAP_STANDARD_PROFILE_ID));
        
            
    }

}